package kong

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/boxer/codegen/core"
	"github.com/boxer/codegen/ir"
)

// DeckConfig generates a Kong declarative config (deck) YAML for the flow.
func DeckConfig(flow *ir.GatewayIR, pluginFilename string) (string, error) {
	upstreams := core.Prerequisites(flow)

	data := struct {
		FlowID         string
		FlowName       string
		Method         string
		Path           string
		PluginFilename string
		Upstreams      []string
	}{
		FlowID:         flow.ID,
		FlowName:       flow.Name,
		Method:         flow.Trigger.Method,
		Path:           flow.Trigger.Path,
		PluginFilename: pluginFilename,
		Upstreams:      upstreams,
	}

	tmpl, err := template.New("deck").Parse(deckTemplate)
	if err != nil {
		return "", fmt.Errorf("deck template parse: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("deck template exec: %w", err)
	}

	return buf.String(), nil
}

const deckTemplate = `# Auto-generated by gateway-codegen
# Flow: {{ .FlowName }} ({{ .FlowID }})
# Apply: deck sync -s kong.yaml

_format_version: "3.0"

services:
  - name: {{ .FlowID }}
    url: http://localhost  # placeholder, plugin handles routing
    routes:
      - name: {{ .FlowID }}-route
        paths:
          - {{ .Path }}
        {{- if ne .Method "ANY" }}
        methods:
          - {{ .Method }}
        {{- end }}
    plugins:
      - name: {{ .FlowID }}
        config:
          handler: {{ .PluginFilename }}

{{ if .Upstreams -}}
upstreams:
{{- range .Upstreams }}
  - name: {{ . }}
    targets:
      - target: {{ . }}.default.svc:80  # adjust to your environment
{{- end }}
{{ end -}}
`
