package kong

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/boxer/codegen/core"
	"github.com/boxer/codegen/ir"
)

type GenerateResult struct {
	Code          string   `json:"code"`
	Filename      string   `json:"filename"`
	Prerequisites []string `json:"prerequisites"`
	Warnings      []string `json:"warnings"`
}

func Generate(flow *ir.GatewayIR) (*GenerateResult, error) {
	infos, order, err := core.AnalyzeGraph(flow)
	if err != nil {
		return nil, fmt.Errorf("graph analysis: %w", err)
	}

	data := buildData(flow, infos, order)

	tmpl, err := template.New("kong").Parse(luaTemplate)
	if err != nil {
		return nil, fmt.Errorf("template parse: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template exec: %w", err)
	}

	return &GenerateResult{
		Code:          buf.String(),
		Filename:      "handler_" + sanitize(flow.ID) + ".lua",
		Prerequisites: core.Prerequisites(flow),
	}, nil
}

// ── Template data ────────────────────────────────────

type tplData struct {
	FlowID   string
	FlowName string
	RootNode string
	Nodes    []tplNode
}

type tplNode struct {
	ID          string
	Type        string
	Upstream    string
	Path        string
	Method      string
	Timeout     int
	Expression  string
	OutputVar   string
	NextNode    string
	TrueBranch  string
	FalseBranch string
	Cases       []tplCase
	DefaultID   string
	Branches    []tplBranch
	JoinNode    string
	InputVars   []string
	Strategy    string
	StatusCode  int
	Body        string
}

type tplCase struct {
	Value    string
	TargetID string
}

type tplBranch struct {
	NodeID    string
	Upstream  string
	Path      string
	Method    string
	Timeout   int
	OutputVar string
}

func buildData(flow *ir.GatewayIR, infos map[string]*core.NodeInfo, order []string) tplData {
	// find root
	hasIncoming := map[string]bool{}
	for _, e := range flow.Edges {
		hasIncoming[e.Target] = true
	}
	root := ""
	for _, n := range flow.Nodes {
		if !hasIncoming[n.ID] {
			root = n.ID
			break
		}
	}

	// inlined fork branches
	inlined := map[string]bool{}
	for _, info := range infos {
		if info.Node.Type == "fork" {
			for _, bid := range info.Branches {
				if bi, ok := infos[bid]; ok && bi.Node.Type == "http-call" {
					inlined[bid] = true
				}
			}
		}
	}

	d := tplData{FlowID: flow.ID, FlowName: flow.Name, RootNode: root}

	for _, id := range order {
		if inlined[id] {
			continue
		}
		info := infos[id]
		n := info.Node

		tn := tplNode{
			ID:          n.ID,
			Type:        n.Type,
			OutputVar:   n.OutputVar,
			NextNode:    info.NextID,
			TrueBranch:  info.TrueBranch,
			FalseBranch: info.FalseBranch,
			DefaultID:   info.DefaultID,
			JoinNode:    info.JoinID,
			InputVars:   info.InputVars,
		}

		switch n.Type {
		case "http-call":
			tn.Upstream = n.GetUpstream().Name
			tn.Path = n.GetString("path")
			tn.Method = n.GetString("method")
			if tn.Method == "" {
				tn.Method = "GET"
			}
			tn.Timeout = n.GetInt("timeout", 3000)
		case "condition":
			tn.Expression = n.GetString("expression")
		case "switch":
			tn.Expression = n.GetString("expression")
			cases := n.GetStringSlice("cases")
			for i, c := range cases {
				target := ""
				if i < len(info.CaseBranch) {
					target = info.CaseBranch[i]
				}
				tn.Cases = append(tn.Cases, tplCase{Value: c, TargetID: target})
			}
		case "transform":
			tn.Expression = n.GetString("expression")
		case "fork":
			tn.Strategy = n.GetString("strategy")
			if tn.Strategy == "" {
				tn.Strategy = "all"
			}
			for _, bid := range info.Branches {
				if bi, ok := infos[bid]; ok && bi.Node.Type == "http-call" {
					bn := bi.Node
					m := bn.GetString("method")
					if m == "" {
						m = "GET"
					}
					tn.Branches = append(tn.Branches, tplBranch{
						NodeID:    bn.ID,
						Upstream:  bn.GetUpstream().Name,
						Path:      bn.GetString("path"),
						Method:    m,
						Timeout:   bn.GetInt("timeout", 3000),
						OutputVar: bn.OutputVar,
					})
				}
			}
		case "join":
			tn.Strategy = n.GetString("strategy")
			if tn.Strategy == "" {
				tn.Strategy = "merge"
			}
			tn.Expression = n.GetString("expression")
		case "response":
			tn.StatusCode = n.GetInt("statusCode", 200)
			tn.Body = n.GetString("body")
		}

		d.Nodes = append(d.Nodes, tn)
	}

	return d
}

// ── Lua template (function-per-node) ─────────────────

const luaTemplate = `-- Auto-generated by gateway-codegen
-- Flow: {{ .FlowName }} ({{ .FlowID }})
-- DO NOT EDIT MANUALLY

local cjson   = require "cjson"
local http    = require "resty.http"
local jsonata = require "resty.jsonata"

local _M = {}

local nodes = {}
{{ range .Nodes }}
{{ if eq .Type "http-call" -}}
-- {{ .ID }}: http-call → {{ .Upstream }}
nodes["{{ .ID }}"] = function(ctx)
  local httpc = http.new()
  local path  = ctx:interpolate("{{ .Path }}")
  local res, err = httpc:request_uri(
    "http://{{ .Upstream }}" .. path,
    { method = "{{ .Method }}", timeout = {{ .Timeout }} }
  )
  if err then
    kong.log.err("{{ .ID }}: ", err)
    kong.response.exit(502, cjson.encode({ error = err }))
  end
  ctx.vars["{{ .OutputVar }}"] = cjson.decode(res.body)
  return "{{ .NextNode }}"
end

{{ else if eq .Type "condition" -}}
-- {{ .ID }}: condition
nodes["{{ .ID }}"] = function(ctx)
  local result = jsonata.evaluate([=[{{ .Expression }}]=], ctx.vars)
  if result then
    return "{{ .TrueBranch }}"
  else
    return "{{ .FalseBranch }}"
  end
end

{{ else if eq .Type "switch" -}}
-- {{ .ID }}: switch
nodes["{{ .ID }}"] = function(ctx)
  local val = tostring(jsonata.evaluate([=[{{ .Expression }}]=], ctx.vars))
  {{ range .Cases -}}
  if val == "{{ .Value }}" then return "{{ .TargetID }}" end
  {{ end -}}
  {{ if .DefaultID -}}
  return "{{ .DefaultID }}"
  {{ else -}}
  kong.response.exit(400, cjson.encode({ error = "no matching case: " .. val }))
  {{ end -}}
end

{{ else if eq .Type "transform" -}}
-- {{ .ID }}: transform
nodes["{{ .ID }}"] = function(ctx)
  ctx.vars["{{ .OutputVar }}"] = jsonata.evaluate([=[{{ .Expression }}]=], ctx.vars)
  return "{{ .NextNode }}"
end

{{ else if eq .Type "fork" -}}
-- {{ .ID }}: fork ({{ .Strategy }})
nodes["{{ .ID }}"] = function(ctx)
  local threads = {}
  {{ range .Branches -}}
  table.insert(threads, ngx.thread.spawn(function()
    local httpc = http.new()
    local path  = ctx:interpolate("{{ .Path }}")
    local res, err = httpc:request_uri(
      "http://{{ .Upstream }}" .. path,
      { method = "{{ .Method }}", timeout = {{ .Timeout }} }
    )
    if not err then
      ctx.vars["{{ .OutputVar }}"] = cjson.decode(res.body)
    end
  end))
  {{ end -}}
  for _, t in ipairs(threads) do ngx.thread.wait(t) end
  return "{{ .JoinNode }}"
end

{{ else if eq .Type "join" -}}
-- {{ .ID }}: join ({{ .Strategy }})
nodes["{{ .ID }}"] = function(ctx)
  {{ if eq .Strategy "merge" -}}
  local merged = {}
  {{ range .InputVars -}}
  if type(ctx.vars["{{ . }}"]) == "table" then
    for k, v in pairs(ctx.vars["{{ . }}"]) do merged[k] = v end
  end
  {{ end -}}
  ctx.vars["{{ .OutputVar }}"] = merged
  {{ else if eq .Strategy "array" -}}
  ctx.vars["{{ .OutputVar }}"] = { {{ range .InputVars }}ctx.vars["{{ . }}"], {{ end }} }
  {{ else -}}
  ctx.vars["{{ .OutputVar }}"] = jsonata.evaluate([=[{{ .Expression }}]=], ctx.vars)
  {{ end -}}
  return "{{ .NextNode }}"
end

{{ else if eq .Type "response" -}}
-- {{ .ID }}: response
nodes["{{ .ID }}"] = function(ctx)
  local body = jsonata.evaluate([=[{{ .Body }}]=], ctx.vars)
  kong.response.exit({{ .StatusCode }}, cjson.encode(body))
  return nil
end

{{ end -}}
{{ end }}
-- Dispatcher
function _M.execute(kong)
  local ctx = {
    params = kong.request.get_uri_captures() or {},
    vars   = {},
  }
  ctx.interpolate = function(self, tmpl)
    return (tmpl:gsub("%${ctx%.params%.(%w+)}", function(k) return self.params[k] or "" end))
  end

  local next_node = "{{ .RootNode }}"
  while next_node do
    local fn = nodes[next_node]
    if not fn then
      kong.response.exit(500, cjson.encode({ error = "unknown node: " .. next_node }))
      return
    end
    next_node = fn(ctx)
  end
end

return _M
`

func sanitize(s string) string {
	return strings.ToLower(strings.NewReplacer("-", "_", " ", "_").Replace(s))
}
